In [16]:
import numpy as np

# Максимум 5 баллов - по ~0.7 баллов за задание

### 1. Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы. 
Для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [17]:
X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]])
# N = 10000
# X = np.random.randint(1, 100, (N, N))
X

array([[1, 0, 1],
       [2, 0, 2],
       [3, 0, 3],
       [4, 4, 4]])

### 1.1

In [18]:
def func1_1(X):
    return np.prod(X.diagonal()[X.diagonal() > 0])
%timeit -n 1000 func1_1(X)
# 4.88 µs ± 234 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each) исходные данные
# 8.73 µs ± 985 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each) N = 1000
# 114 µs ± 6.57 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each) N = 10000

1000 loops, best of 5: 6.37 µs per loop


### 1.2

In [19]:
def func1_2(X):
    return np.prod([X[i][i] for i in range(np.min(X.shape)) if X[i][i] != 0])
%timeit -n 1000 func1_2(X)
# 10.1 µs ± 1.14 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each) исходные данные
# 558 µs ± 7.99 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each) N = 1000
# 5.9 ms ± 353 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each) N = 10000

1000 loops, best of 5: 14.1 µs per loop


### 1.3

In [20]:
def func1_3(X):
    X_diagonal = X.diagonal()
    items_g0 = X_diagonal > 0
    return np.prod(X_diagonal[items_g0])
%timeit -n 1000 func1_3(X)
# 5.7 µs ± 1.05 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each) исходные данные
# 8.44 µs ± 661 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each) N = 1000
# 104 µs ± 2.1 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each) N = 10000

1000 loops, best of 5: 6.01 µs per loop


### Выводы
1) Способ решения с векторами самый быстрый

2) Способ решения с циклами - самый медленный

3) наиболее хорошо читаемый код получился лучше решения с циклами, но хуже варианта с векторами

### 2. Дана матрица X и два вектора одинаковой длины i и j. Построить вектор np.array([X[i[0], j[0]], X[i[1], j[1]], ... , X[i[N-1], j[N-1]]]).

In [21]:
i = np.array([1, 7, 3, 4])
j = np.array([1, 2, 3, 8])
# N = 100
# i = np.random.randint(0, N, N)
# j = np.random.randint(0, N, N)
X = np.random.randint(0, 100, (np.max(i) + 1, np.max(j) + 1))
X

array([[47, 74, 95, 71, 10, 74, 62, 13, 11],
       [86, 17, 96, 56, 77, 83, 77, 88, 39],
       [85, 97, 57, 19, 97, 17, 29, 30, 13],
       [40, 70, 91, 37, 50, 49, 18, 12, 66],
       [13, 47, 33, 35, 42, 50, 21, 91, 11],
       [61, 66,  1, 10, 44, 45, 63, 67, 88],
       [36, 30, 97, 31,  5, 43,  9,  2, 50],
       [41, 91, 78,  7, 38, 48, 59,  5, 90]])

### 2.1

In [22]:
def func2_1(X, i, j):
    return X[i, j]
%timeit -n 100 func2_1(X, i, j)
func2_1(X, i, j)
# 4.29 µs ± 5.64 µs per loop (mean ± std. dev. of 7 runs, 100 loops each) N = 100
# 9.24 µs ± 5.22 µs per loop (mean ± std. dev. of 7 runs, 100 loops each) N = 1000
# 141 µs ± 15.1 µs per loop (mean ± std. dev. of 7 runs, 100 loops each) N = 10000

100 loops, best of 5: 1.86 µs per loop


array([17, 78, 37, 11])

### 2.2

In [23]:
def func2_2(X, i, j):
    return np.array([X[i[k]][j[k]] for k in range(len(i))])
%timeit -n 100 func2_2(X, i, j)
func2_2(X, i, j)
# 51.3 µs ± 1.35 µs per loop (mean ± std. dev. of 7 runs, 100 loops each) N = 100
# 461 µs ± 6.88 µs per loop (mean ± std. dev. of 7 runs, 100 loops each) N = 1000
# 5.58 ms ± 757 µs per loop (mean ± std. dev. of 7 runs, 100 loops each) N = 10000

100 loops, best of 5: 3.52 µs per loop


array([17, 78, 37, 11])

### 2.3

In [24]:
def func2_3(X, i, j):
    result = []
    for k in range(len(i)):
        result.append(X[i[k], j[k]])
    return result
%timeit -n 100 func2_3(X, i, j)
# 37.6 µs ± 2.88 µs per loop (mean ± std. dev. of 7 runs, 100 loops each) N = 100
# 475 µs ± 46.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each) N = 1000
# 4.01 ms ± 161 µs per loop (mean ± std. dev. of 7 runs, 100 loops each) N = 1000

100 loops, best of 5: 3.68 µs per loop


### Вывод
1) Способ решения с векторами самый быстрый

2) Способ решения с циклами - самый медленный

3) наиболее хорошо читаемый код получился лучше решения с циклами, но хуже варианта с векторами

### 3. Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество. 
Для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [25]:
N = 100
x = np.random.randint(0, 2 * N, N)
y = np.random.randint(0, 2 * N, N)
# x = np.array([1, 2, 2, 3, 3])
# y = np.array([4, 2, 1, 2, 3])
print(x, '\n', y)

[ 33  79 126 145  92 138  70  55 193  98   5  13 182  71 147  73 125 149
 136  79   6  58 153  64  48  30 108   0  88   6 123 130 171  51  86 175
  61 137   7  66  23  22  73  68  81 197 147  51  29  85  80  88  87  18
  17 157 124  97 180 125 118 127  40  81 120 146  54 182 170  38  98 193
  99  72  45  40 135  28 163 160 118 166  49 195  36  95  21  54 167  18
 175 169  94  41 111 172 164 114  23 156] 
 [172  84 178  97 165 135  68  21  18 181  96 114 163  52  12 191 158 122
 157  50  95 133  84  65  59 115  59  37 106 103  25 134  48  76 173  19
  23 187  47 170 188 120 139  75 114 197 181  57  98 195   1 104  18 154
 149  45 182 188  59  34 110 125  41  20 192 172 122  10  28  54  23   6
  26 159 107 174  26  89 156 169  29 115  29  45 106  45  54  33 157 179
   8 132  55  47 139  81   8  61  50 192]


### 3.1

In [26]:
def func3_1(x, y):
    bool_list = np.sort(x) == np.sort(y)
    if x[bool_list].shape[0] == x.shape[0]:
        return True
    return False
%timeit -n 100 func3_1(x, y)
func3_1(x, y)
# 6.83 µs ± 2.92 µs per loop (mean ± std. dev. of 7 runs, 100 loops each) N = 100
# 41.9 µs ± 7.62 µs per loop (mean ± std. dev. of 7 runs, 100 loops each) N = 1000
# 1.12 ms ± 33.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each) N = 10000

100 loops, best of 5: 9.65 µs per loop


False

### 3.2

In [27]:
def func3_2(x, y):
    x = np.sort(x)
    y = np.sort(y)
    for i in range(len(x)):
        if x[i] != y[i]:
            return False
    return True

%timeit -n 100 func3_2(x, y)
func3_2(x, y)
# 5.3 µs ± 3.01 µs per loop (mean ± std. dev. of 7 runs, 100 loops each) N = 100
# 35.2 µs ± 7.8 µs per loop (mean ± std. dev. of 7 runs, 100 loops each) N = 1000
# 1.38 ms ± 379 µs per loop (mean ± std. dev. of 7 runs, 100 loops each) N = 10000

100 loops, best of 5: 4.62 µs per loop


False

### 3.3

In [28]:
def func3_3(x, y):
    for i in x:
        if np.sum(x == i) != np.sum(y == i):
            return False
    return True
%timeit -n 100 func3_3(x, y)
func3_3(x, y)
# 18.8 µs ± 988 ns per loop (mean ± std. dev. of 7 runs, 100 loops each) N = 100
# 18.8 µs ± 6.25 µs per loop (mean ± std. dev. of 7 runs, 100 loops each) N = 1000
# 64.5 µs ± 6.02 µs per loop (mean ± std. dev. of 7 runs, 100 loops each) N = 10000

100 loops, best of 5: 24.5 µs per loop


False

### Вывод
1) Способ решения с векторами оказался хуже, чем с циклами

2) Способ решения с циклами - самый быстрый

3) Третий способ проверки в цикле кол-ва каждого элемента с применением векторизации оказался наихудхим вариантом

### 4. Найти максимальный элемент в векторе x среди элементов, перед которыми стоит нулевой.
Для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [29]:
# x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
N = 100
x = np.random.randint(0, 100, N)
x

array([96,  6, 51, 17, 90,  2, 91, 66, 12,  4, 59, 65, 91, 32, 24, 21, 70,
       12, 30, 68, 87, 97, 15, 43, 18, 11, 78, 13, 69, 72,  7, 90,  6, 88,
       23, 40,  1, 79, 81, 46, 80,  4,  3, 98, 94, 81, 39, 86, 41, 18, 43,
       77, 68, 51, 80,  4, 69, 42, 47, 29, 45, 54, 39, 75, 99, 88, 33, 99,
       99, 44,  5,  4, 31, 34, 10, 13, 53, 75, 25, 56, 77, 41, 53, 72, 75,
       67, 56, 44, 78, 29,  5, 37, 96, 55, 72, 73,  9, 73, 98, 43])

### 4.1

In [35]:
def func4_1(x):
    v = x == 0
    bool_mass = np.concatenate([[False], v])[:-1]
    if np.sum(bool_mass) == 0:
      return -1
    return np.max(x[bool_mass])
%timeit -n 100 func4_1(x)
func4_1(x)
# 7.97 µs ± 2.38 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each) N = 100
# 10.1 µs ± 5.16 µs per loop (mean ± std. dev. of 7 runs, 100 loops each) N = 1000
# 19.6 µs ± 6.43 µs per loop (mean ± std. dev. of 7 runs, 100 loops each) N = 10000

100 loops, best of 5: 16.4 µs per loop


0

### 4.2

In [ ]:
def func4_2(x):
    max = -100_000
    for i in range(x.shape[0] - 1):
        if (x[i] == 0):
            if (x[i + 1] > max):
                max = x[i + 1]
    return max
%timeit -n 100 func4_2(x)
func4_2(x)
# 24.8 µs ± 2.09 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each) N = 100
# 208 µs ± 14.1 µs per loop (mean ± std. dev. of 7 runs, 100 loops each) N = 1000
# 2.2 ms ± 222 µs per loop (mean ± std. dev. of 7 runs, 100 loops each) N = 10000

23.6 µs ± 1.06 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


93

### 4.3

In [ ]:
def func4_3(x):
    is_x_index_zero = x == 0
    bool_x_after_zero = np.concatenate([[False], is_x_index_zero])[:-1]
    return np.max(bool_x_after_zero)
%timeit -n 100 func4_2(x)
func4_3(x)
# 21.8 µs ± 2.15 µs per loop (mean ± std. dev. of 7 runs, 100 loops each) N = 100
# 210 µs ± 3.29 µs per loop (mean ± std. dev. of 7 runs, 100 loops each) N = 1000
# 2.69 ms ± 732 µs per loop (mean ± std. dev. of 7 runs, 100 loops each) N = 10000

The slowest run took 5.50 times longer than the fastest. This could mean that an intermediate result is being cached.
36.9 µs ± 34.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


True

### Вывод
1) Способ решения с векторами - самый эффективный

2) Способ решения с помощью сдвига индекса нулевых значений оказался самым худшим

3) Третий способ решения одного порядка с решением с циклами

### 5. Дан трёхмерный массив, содержащий изображение, размера (height, width, numChannels), а также вектор длины numChannels. Сложить каналы изображения с указанными весами, и вернуть результат в виде матрицы размера (height, width). Считать реальное изображение можно при помощи функции scipy.misc.imread (если изображение не в формате png, установите пакет pillow: conda install pillow). Преобразуйте цветное изображение в оттенки серого, использовав коэффициенты np.array([0.299, 0.587, 0.114]).

In [36]:
import imageio

In [50]:
N = 100
img = np.arange(N * N * 3).reshape(N, -1, 3)
weights = np.array([0.299, 0.587, 0.114])
# img = imageio.imread("1-campos-amapolas.jpg")
img.shape

(100, 100, 3)

### 5.1

In [51]:
def func5_1(img, weights):
    return img.dot(weights)
%timeit -n 100 func5_1(img, weights)
# imageio.imwrite(uri="1-campos-amapolas_grey.jpg", im=func5_1(img, weights))
# 189 µs ± 13.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each) N = 100
# 21.8 ms ± 2.38 ms per loop (mean ± std. dev. of 7 runs, 100 loops each) N = 1000

100 loops, best of 5: 275 µs per loop


### 5.2

In [52]:
def func5_2(img, wetghts):
    result = np.zeros((img.shape[0], img.shape[1]))
    for i in range(wetghts.shape[0]):
        result += img[:, :, i] * weights[i]
    return result
%timeit -n 100 func5_2(img, weights)
# 116 µs ± 93.8 µs per loop (mean ± std. dev. of 7 runs, 100 loops each) N = 100
# 7.49 ms ± 113 µs per loop (mean ± std. dev. of 7 runs, 100 loops each) N = 1000

100 loops, best of 5: 60.9 µs per loop


### 5.3

In [53]:
def func5_3(img, wetghts):
    X = lambda i: img[:, :, i] * wetghts[i]
    return X(0) + X(1) + X(2)
%timeit -n 100 func5_3(img, weights)
# 2.77 ms ± 796 µs per loop (mean ± std. dev. of 7 runs, 100 loops each) N = 100
# 7.35 ms ± 1.5 ms per loop (mean ± std. dev. of 7 runs, 100 loops each) N = 1000

100 loops, best of 5: 54 µs per loop


### Вывод
1) Способ решения с векторами оказался хуже, чем с циклами

2) Способ решения с помощью лямбда функции оказался лучше способа с векторами при большом N

3) Способ решения с помощью лямбда функции оказался плохим при малом N

4) Спрособ решения с циклами в данном случае является самым оптимальным из 3-х алгоритмов

### 6. Реализовать кодирование длин серий (Run-length encoding). Дан вектор x. Необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить. 
Пример: x = np.array([2, 2, 2, 3, 3, 3, 5]). Ответ: (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [54]:
x = np.array([2, 2, 2, 3, 3, 3, 5, 3, 2, 2 ,1])
# N = 100
# x = np.random.randint(0, 10, N)
x

array([2, 2, 2, 3, 3, 3, 5, 3, 2, 2, 1])

### 6.1

In [59]:
def func6_1(x):
    vals, ids, counts = np.unique(x, return_index=True, return_counts=True)
    index = np.argsort(ids)
    return vals[index], counts[index]
print(func6_1(x))

(array([2, 3, 5, 1]), array([5, 4, 1, 1]))


### 6.2

In [60]:
def func6_2(x):
    result_key = [x[0]]
    result_item = [1]
    for i in range(1, x.shape[0]):
        if x[i] == result_key[-1]:
            result_item[-1] += 1
        else:
            result_key.append(x[i])
            result_item.append(1)
    return result_key, result_item
%timeit -n 100 func6_2(x)
print(func6_2(x))
# 31.6 µs ± 3.52 µs per loop (mean ± std. dev. of 7 runs, 100 loops each) N = 100
# 290 µs ± 35.8 µs per loop (mean ± std. dev. of 7 runs, 100 loops each) N = 1000
# 3.16 ms ± 658 µs per loop (mean ± std. dev. of 7 runs, 100 loops each) N = 10000

100 loops, best of 5: 4.52 µs per loop
([2, 3, 5, 3, 2, 1], [3, 3, 1, 1, 2, 1])


### 6.3

In [61]:
from itertools import groupby

In [62]:
def func6_3(x):
    _key = []
    _item = []
    for key, group in groupby(x):
        _key.append(key)
        _item.append(len(tuple(group)))
    return _key, _item
%timeit -n 100 func6_3(x)
# 39.5 µs ± 1.23 µs per loop (mean ± std. dev. of 7 runs, 100 loops each) N = 100
# 385 µs ± 8.82 µs per loop (mean ± std. dev. of 7 runs, 100 loops each) N = 1000
# 3.57 ms ± 32.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each) N = 10000

100 loops, best of 5: 5.25 µs per loop


### Вывод
1) Способ решения с циклами и с применением groupby из библиотеки itertools обладают одинаковым ростом времени работы в зависимости от N

2) Способ решения с циклами немного быстрее, чем 3-й способ

### 7. Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравнить с функцией scipy.spatial.distance.cdist.

In [63]:
from scipy.spatial.distance import cdist

In [64]:
N = 100
X = np.random.randint(0, 100, (N, N))
Y = np.random.randint(0, 100, (N, N))
print(X, Y)

[[11 13 31 ... 36 85 57]
 [31 64 79 ... 33 22  6]
 [68  9 18 ... 54 16 65]
 ...
 [57 19 68 ... 55 45 10]
 [78 27 88 ... 39 40 42]
 [39  1  6 ... 97 82  3]] [[27 41 15 ... 36 32 69]
 [96 18 55 ... 59 60 33]
 [ 8 84 23 ... 73 69 38]
 ...
 [97 52 17 ... 65 19  8]
 [58 85 39 ... 44 80 26]
 [10  5 79 ... 16 74 93]]


### 7.1

In [65]:
def func7_1(x, y):
    P = np.add.outer(np.sum(x**2, axis=1), np.sum(y**2, axis=1))
    N = np.dot(x, y.T)
    return np.sqrt(P - 2*N)
# print(cdist(X, Y) - func7_1(X, Y))
%timeit -n 10 func7_1(X, Y)
# 699 µs ± 30.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each) N = 100
# 620 ms ± 45 ms per loop (mean ± std. dev. of 7 runs, 1 loop each) N = 1000
# 5.05 s ± 408 ms per loop (mean ± std. dev. of 7 runs, 1 loop each) N = 2000

10 loops, best of 5: 1.21 ms per loop


### 7.2

In [66]:
def func7_2(x, y):
    d = np.zeros_like(x)
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            d[i, j] = np.sum(abs(x[i, :] - y[j, :]) ** 2)
    return np.sqrt(d)
print(cdist(X, Y) - func7_2(X, Y))
%timeit -n 10 func7_2(X, Y)
# 48.3 ms ± 3.89 ms per loop (mean ± std. dev. of 7 runs, 10 loops each) N = 100
# 6.63 s ± 104 ms per loop (mean ± std. dev. of 7 runs, 1 loop each) N = 1000

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
10 loops, best of 5: 75.3 ms per loop


### 7.3

In [67]:
def func7_3(X, Y):
    YT = Y.transpose()
    vecProd = np.dot(X,YT)

    SqX =  X**2
    sumSqX = np.matrix(np.sum(SqX, axis=1))
    sumSqXEx = np.tile(sumSqX.transpose(), (1, vecProd.shape[1]))

    SqY = Y**2
    sumSqY = np.matrix(np.sum(SqY, axis=1))
    sumSqYEx = np.tile(sumSqY, (vecProd.shape[0], 1))

    SqED = sumSqYEx + sumSqXEx - 2*vecProd
    SqED[SqED<0]=0.0
    ED = np.sqrt(SqED)
    return ED
# print(cdist(X, Y) - func7_3(X, Y))
%timeit -n 10 func7_3(X, Y)
# 1.07 ms ± 321 µs per loop (mean ± std. dev. of 7 runs, 10 loops each) N = 100
# 617 ms ± 17.8 ms per loop (mean ± std. dev. of 7 runs, 10 loops each) N = 1000
# 4.72 s ± 563 ms per loop (mean ± std. dev. of 7 runs, 1 loop each) N = 2000

10 loops, best of 5: 1.31 ms per loop


### Вывод
1) Способ решения с векторами оказался намного лучше, чем с циклами
2) Скорость роста времени работы от N способа решения с циклами на порядок меньше, чем у способа с векторами
3) Эффективность третьего способа решения (наиболее хорошо читаемый способ) в среднем аналогична решения с циклами.
4) Результат корректности выполнения алгоритма выполняется с помощью функции from scipy.spatial.distance.cdist(X, Y)

##### Замечание. Можно считать, что все указанные объекты непустые (к примеру, в задаче №1 на диагонали матрицы есть ненулевые элементы).
Полезные функции NumPy: np.zeros, np.ones, np.diag, np.eye, np.arange, np.linspace, np.meshgrid,
np.random.random, np.random.randint, np.shape, np.reshape, np.transpose, np.any, np.all, np.nonzero, np.where,
np.sum, np.cumsum, np.prod, np.diff, np.min, np.max, np.minimum, np.maximum, np.argmin, np.argmax, np.unique,
np.sort, np.argsort, np.bincount, np.ravel, np.newaxis, np.dot, np.linalg.inv, np.linalg.solve.
Многие из этих функций можно использовать так: x.argmin().

# Для каждой из задач:
(a) Написать на Python + NumPy несколько вариантов кода различной эффективности. Должно быть не
менее трёх вариантов, в том числе как минимум один полностью векторизованный вариант (без циклов), и один
вариант без векторизации (с циклами). Третий вариант решения — на ваше усмотрение, например, это может быть
наиболее хорошо читаемый способ решения, или частично векторизованный вариант. Все пункты выполнять в одном google collab, разделяя их пунктами 1., 1.1, 1.2, 1.3; 2., 2.1, 2.2, 2.3; и тд.

(b) Сравнить в IPython Notebook при помощи %timeit скорость работы на нескольких тестовых наборах
РАЗНОГО размера (минимум 3, причём отличаться размеры входных данных должны минимум на порядок. Например, массивы длины 100, 1000, 10000).

(c) Проанализировать полученные данные о скорости работы разных реализаций.

(d) Получить выводы.